### PR TITLE
fix skill

### PR DESCRIPTION
**Pull request by xiaozhu0232**

### CODE REVIEW

**Comment by GenusLi** [comment]
There are many errors in the merged skill profiles, for example, the field (group) of txt file in buff does not match the field (groupid) of GameBuff class

**Comment by xiaozhu0232** [comment]
I tested it locally

**Comment by xiaozhu0232** [comment]
image

**Comment by AlanWeekend** [comment]
> I tested it locally

Thanks for you pr,The Gourp field in the text does not exist in the CSharp script, so the Group field is invalid. The GroupId of the CSharp script does not get it because of the deserialization. It will be a default value. I tested your Pr, and the "魔旋天刃-无铭文" skill is still invalid. I have tried to repair it, and now it seems that I have succeeded. This is a program problem that cannot be solved by modifying the configuration file.The fact that your Winform program can be executed only means that no fatal error has occurred. This is an inevitable result, because usually modifying the configuration file will not lead to a fatal error. You should test whether your changes are really effective in the game, rather than determine whether the program can be executed correctly.Invalid and incorrect modifications will affect the stability of the main branch

**Comment by bernatvadell** [comment]
Please review changes, some files are incorrect.

**Pull request merged**
